### ISSUE TITLE
Wanting to rebase my pull request & had a thought about the format

### ISSUE THREAD

**Issue by yellownoggin** [pimentel/voicecode_directory#3]
pull request
#2

Rebased it locally and squashed all those commits into one. But didn't reflect in the remote.
Not a huge deal for me, but figured since it wasn't merged yet i would shoot over a message.

Also,  first of all, it is an awesome idea, and I think it is/can be very useful. 

But,  while doing this it came to me to make a suggestion on it overall. 

**question/thought on format**
Wouldn't it be better or more maintainable for yourself/in general to just include a couple of things on the main voicecode directory page? 

For example, 1) voicecode slack handle, 2) the Configuration on GitHub link, 3) a My Voicecode Profile Page link (that the person can maintain or update anywhere without having to make pull request)

Example output: 
### Jamie (John) Hennelly
- Nick(Handle) on Slack: @jjhennelly
- [Configuration on Github](https://github.com/yellownoggin/toolbox/tree/master/dotfiles/voicecode/commando)
- [My Voicecode Profile Page on Github](https://github.com/yellownoggin/toolbox/tree/master/dotfiles/voicecode)

Last point:  and maybe even the handle should also just be maintained on one's profile page in the case where the voicecode stops using Slack and/or a person may change their handle name.

**Comment by pimentel** [comment]
Hey John,

Really sorry about the delay. I agree with your comments about the format and maintainability. Honestly, I kind of want to keep it as unstructured as possible so if people want a limited profile than they totally should. I will add this into the readme shortly along with some of your other points.

Thanks!

**Comment by yellownoggin** [comment]
No problem at all: -) 
Yes, I agree about the unstructured point & nothing being required. I think the most important part is the configuration files as you pointed out as the main purpose in the README. Feeding off of other people's set ups in general is super helpful,  Of course you'll want to have still have something personalized, but less reinventing of the wheel is good.

Overall, awesome idea. Thank you.
